### ISSUE TITLE
CLI and Module Names are different and leading to Confusion

### ISSUE THREAD

**Issue by mthipparthi** [asottile/pytest-gevent#2]
Description. Thanks for the package. It was really helpful. When this package is independently run as cli we use in tox `**pytest-gevent** {posargs:./test}` . However if this has to be as module . for eg : `coverage run --concurrency=gevent --source '{toxinidir}' --omit='{envdir}*' -m **pytest_gevent**` . This leads to confusion.

**Comment by asottile** [comment]
- module names can't have dashes
- the de facto standard for command line tools is to use dashes

I'm sorry you're confused but this is fairly standard practice

**Comment by mthipparthi** [comment]
Thanks for that. Glad to know that is practise.
